Emlakcilik/Models/EntityFramework/Ilan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlakcilik.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilan
    {
        public int IlanId { get; set; }
        public int IlanTipId { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public int SehirId { get; set; }
        public int IlceId { get; set; }
        public int GayrimenkulId { get; set; }
    
        public virtual Gayrimenkul Gayrimenkul { get; set; }
        public virtual IlanTip IlanTip { get; set; }
        public virtual Ilce Ilce { get; set; }
        public virtual Sehir Sehir { get; set; }
    }
}

Emlakcilik/Controllers/IlanController.cs
using Emlakcilik.Models.EntityFramework;
using Emlakcilik.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Emlakcilik.Controllers
{
    public class IlanController : Controller
    {
        emlakcilikEntities db = new emlakcilikEntities();
        // GET: Ilan
        public ActionResult Index()
        {
            var model = db.Ilan.ToList();
            return View(model);
        }
         public ActionResult Yeni()
         {
            var model = new IlanFormViewModel()
            {
                Tipler=db.IlanTip.ToList(),
                Gayrimenkuller=db.Gayrimenkul.ToList(),
                Sehirler=db.Sehir.ToList(),
                Ilceler=db.Ilce.ToList()
            };
             return View("IlanForm",model); 
         } 

         public ActionResult Kaydet(Ilan ilan)
        {
         
                if (ilan.IlanId == 0)
                {
                   
                    db.Ilan.Add(ilan);
                    db.SaveChanges();
                }
             
            return RedirectToAction("Index");
        }






    }
}

Emlakcilik/Views/Ilan/IlanForm.cshtml
@model Emlakcilik.ViewModels.IlanFormViewModel

@{ 
    ViewBag.Title = "IlanForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ilan Formu</h2>
@using (Html.BeginForm("Kaydet", "Ilan", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.ilan.IlanId)
        @Html.TextBoxFor(m => m.ilan.IlanId,new { @class="form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ilan.IlanTip.IlanTipi)
        @Html.DropDownListFor(m => m.ilan.IlanTipId,new SelectList(Model.Tipler, "Id","IlanTipi"),"İlan Tipi Seçiniz...",new { @class="form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ilan.Fiyat)
        @Html.TextBoxFor(m => m.ilan.Fiyat, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ilan.Tarih)
        @Html.TextBoxFor(m => m.ilan.Tarih, new { @class = "form-control" })
    </div> 
    <div class="form-group">
        @Html.LabelFor(m => m.ilan.Sehir.Ad)
        @Html.DropDownListFor(m => m.ilan.SehirId, new SelectList(Model.Sehirler, "Id", "Ad"),"Şehir Seçiniz...", new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ilan.Ilce.Ad)
        @Html.DropDownListFor(m => m.ilan.IlceId, new SelectList(Model.Ilceler, "Id", "Ad"),"İlçe Seçiniz...", new { @class = "form-control" })
    </div>
   <div class="form-group">
        @Html.LabelFor(m => m.ilan.Gayrimenkul.Adres)
        @Html.DropDownListFor(m=>m.ilan.GayrimenkulId,new SelectList(Model.Gayrimenkuller,"Id","Adres"),"Adres Seçiniz...",new { @class="form-control"})
    </div>
    <button type="submit" class="btn btn-default">Kaydet</button>
}

Emlakcilik/Views/Ilan/Index.cshtml
@model List<Emlakcilik.Models.EntityFramework.Ilan>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ActionLink("Yeni İlan","Yeni",null,new {@class="btn btn-success" })

<h2>Ilan Listesi</h2>

<table class="table table-bordered" >
      <thead>
          <tr>
              <th>Ilan Id</th>
              <th>Ilan Tipi</th>
              <th>Fiyatı</th>
              <th>Tarihi</th>
              <th>Şehir</th>
              <th>İlçe</th>
              <th>Gayrimenkul Adresi</th>
          </tr>
      </thead>
      <tbody>
          @foreach (var ilan in Model)
          {
              <tr>
                  <td>@ilan.IlanId</td>
                  <td>@ilan.IlanTip.IlanTipi</td>
                  <td>@ilan.Fiyat</td>
                  <td>@ilan.Tarih.Value.ToString("dd-MM-yyyy")</td>
                  <td>@ilan.Sehir.Ad</td>
                  <td>@ilan.Ilce.Ad</td>
                  <td>@ilan.Gayrimenkul.Adres</td>

              </tr>
          }

      </tbody>
</table>